### ISSUE TITLE
6.2.2版本启用hanlp后es就关闭

### ISSUE THREAD

**Issue by JnuLuX** [KennFalcon/elasticsearch-analysis-hanlp#10]
使用方式二安装hanlp插件，安装过程顺利，es也正常启动了，但是在kibana里面测试hanlp：
GET /_analyze?pretty
{
  "analyzer" : "hanlp",
  "text" : ["重庆华龙网海数科技有限公司"]
}
发现es关闭了，检查log如下：
[2018-09-06T09:15:39,827][ERROR][c.h.d.Monitor            ] can not find hanlp.properties
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_181]
    at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_181]
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_181]
    at java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:1528) ~[?:1.8.0_181]
    at java.lang.Thread.getContextClassLoader(Thread.java:1443) ~[?:1.8.0_181]
    at com.hankcs.dic.Monitor.reloadProperty(Monitor.java:61) [elasticsearch-analysis-hanlp-6.2.2.jar:?]
    at com.hankcs.dic.Monitor.run(Monitor.java:34) [elasticsearch-analysis-hanlp-6.2.2.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[2018-09-06T09:16:23,505][INFO ][o.e.m.j.JvmGcMonitorService] [cyVG2fn] [gc][57] overhead, spent [318ms] collecting in the last [1s]
[2018-09-06T09:35:31,918][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[cyVG2fn][index][T#1]], exiting
java.lang.NoClassDefFoundError: Could not initialize class com.hankcs.hanlp.HanLP$Config
    at com.hankcs.hanlp.seg.Segment.seg(Segment.java:423) ~[?:?]
    at com.hankcs.lucene.SegmentWrapper.next(SegmentWrapper.java:76) ~[?:?]
    at com.hankcs.lucene.HanLPTokenizer.incrementToken(HanLPTokenizer.java:94) ~[?:?]
    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:266) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:243) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:164) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:80) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:293) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:286) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.2.jar:6.2.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by KennFalcon** [comment]
麻烦确认一下hanlp.properties的位置是否正确，应该存在ES_HOME/config/analysis-hanlp目录下

**Comment by JnuLuX** [comment]
我在/etc/elasticsearch以及/usr/share/elasticsearch/config都放了hanlp.properties，不知道是什么原因导致这个状况发生的。
同时近期测试了6.3.2版本，这个版本完全没问题。
另外，请问有6.2.4版本的插件吗？
