### ISSUE TITLE
在es 7.10环境 安装ERROR

### ISSUE THREAD

**Issue by yaleimeng** [KennFalcon/elasticsearch-analysis-hanlp#105]
从网盘下载了最新的7.9.0.zip包，但是安装时报错。
我es版本是7.10.2，从readme说明看似乎是可以支持的，但报错里面提示版本不支持？
root@===# bin/elasticsearch-plugin install file:///home/elastic/analysis-hanlp-7.9.0.zip 
future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jdk/jdk1.8.0_171/jre] does not meet this requirement
-> Installing file:///home/elastic/analysis-hanlp-7.9.0.zip
-> Downloading file:///home/elastic/analysis-hanlp-7.9.0.zip
[=================================================] 100%   
-> Failed installing file:///home/elastic/analysis-hanlp-7.9.0.zip
-> Rolling back file:///home/elastic/analysis-hanlp-7.9.0.zip
-> Rolled back file:///home/elastic/analysis-hanlp-7.9.0.zip
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [analysis-hanlp] was built for Elasticsearch version 7.9.0 but version 7.10.2 is running
        at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:352)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:811)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:866)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:254)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by yaleimeng** [comment]
ES降级到7.9.0，能安装成功。
命令形式为： bin/elasticsearch-plugin install file:///home/elastic/analysis-hanlp-7.9.0.zip
但7.10环境不能正常安装。

**Comment by KennFalcon** [comment]
7.9.0之后的版本我这几天抽空测试后会上传上去

Yalei Meng <notifications@github.com> 于2021年2月3日周三 下午1:20写道：

**Comment by KennFalcon** [comment]
已打包上传7.10.0~7.10.2版本，请自行下载

**Comment by yaleimeng** [comment]
非常感谢您的付出和分享！
