### ISSUE TITLE
elasticsearch 7.10.2 rpm 安装，安装elasticsearch-analysis-hanlp 7.10.2 之后，启动失败

### ISSUE THREAD

**Issue by openmartin** [KennFalcon/elasticsearch-analysis-hanlp#106]
elasticsearch 7.10.2
安装 elasticsearch-analysis-hanlp 7.10.2 之后启动失败

貌似是 Hanlp 初始化的问题
https://github.com/hankcs/HanLP/blob/180f7c0cd2083762aabcc2def9b3a13c4c77b675/src/main/java/com/hankcs/hanlp/HanLP.java#L247

在 /etc/sysconfig/elasticsearch 中添加环境变量之后启动正常
HANLP_ROOT=/usr/share/elasticsearch/plugins/analysis-hanlp/

**Comment by openmartin** [comment]
报错日志如下：

```
fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError
at org.elasticsearch.plugin.analysis.hanlp.AnalysisHanLPPlugin.lambda$getTokenizers$0(AnalysisHanLPPlugin.java:67)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
at org.elasticsearch.plugin.analysis.hanlp.AnalysisHanLPPlugin.getTokenizers(AnalysisHanLPPlugin.java:67)
at org.elasticsearch.common.NamedRegistry.extractAndRegister(NamedRegistry.java:54)
at org.elasticsearch.indices.analysis.AnalysisModule.setupTokenizers(AnalysisModule.java:237)
at org.elasticsearch.indices.analysis.AnalysisModule.<init>(AnalysisModule.java:83)
at org.elasticsearch.node.Node.<init>(Node.java:396)
at org.elasticsearch.node.Node.<init>(Node.java:289)
at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)
at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
at org.elasticsearch.cli.Command.main(Command.java:90)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "data/dictionary/CoreNatureDictionary.tr.tx
at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
at java.base/java.security.AccessController.checkPermission(AccessController.java:1036)
at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:747)
at java.base/java.io.File.isFile(File.java:880)
at com.hankcs.hanlp.HanLP$Config.<clinit>(HanLP.java:335)
```

**Comment by KennFalcon** [comment]
因为rpm包安装的elasticsearch的路径和普通压缩包安装的不太一样导致，后续会考虑该问题，建议先采用普通压缩包安装解决

openmartin <notifications@github.com> 于2021年2月5日周五 下午4:06写道：

**Comment by neulf** [comment]
me too.

**Comment by jdkcn** [comment]
docker 安装的一样错误。
通过 `ES_JAVA_OPTS` 配置解决，能否在文档中说明一下。

`ES_JAVA_OPTS="-DHANLP_ROOT=/usr/share/elasticsearch/plugins/analysis-hanlp"`

**Comment by hbzhu** [comment]
我在kubernetes添加了环境变量ES_JAVA_OPTS="-DHANLP_ROOT=/usr/share/elasticsearch/plugins/analysis-hanlp"，仍然提示plugin policy [/usr/share/elasticsearch/plugins/analysis-hanlp/plugin-security.policy] contains illegal permission ("java.io.FilePermission" "plugins/analysis-hanlp/data/-#plus" "read,write,delete")

**Comment by ch219318** [comment]
@jdkcn 
更好的修改java_opts方式：
如果是rpm安装的es：
vim /etc/elasticsearch/jvm.options.d/hanlp.options
填写内容如下
-DHANLP_ROOT=/usr/share/elasticsearch/plugins/analysis-hanlp
