### ISSUE TITLE
启动报错找不到配置文件

### ISSUE THREAD

**Issue by DongYuLiu-Boss** [KennFalcon/elasticsearch-analysis-hanlp#143]
我使用的版本是Tag V7.9.3，ES采用RPM包安装到Linux服务器中，启动服务报错如下：
11月 29 00:04:56 VM-16-3-centos systemd-entrypoint[7568]: at java.base/java.security.AccessController.checkPermission(AccessController.java:1036)
11月 29 00:04:56 VM-16-3-centos systemd-entrypoint[7568]: at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
11月 29 00:04:56 VM-16-3-centos systemd-entrypoint[7568]: at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:747)
11月 29 00:04:56 VM-16-3-centos systemd-entrypoint[7568]: at java.base/java.io.File.isFile(File.java:880)
11月 29 00:04:56 VM-16-3-centos systemd-entrypoint[7568]: at com.hankcs.hanlp.HanLP$Config.<clinit>(HanLP.java:335)

**Comment by quanwuhui** [comment]
如果是linux rpm包安装的可以参照如下步骤。
1. /etc/sysconfig/elasticsearch文件加配置项 HANLP_ROOT=/usr/share/elasticsearch/plugins/analysis-hanlp/
2. 修改目录权限，chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/plugins/
3. 将rpm包安装后配置文件目录默认的/etc/elasticsearch 移动到/usr/share/elasticsearch/config，并修改对应的/etc/sysconfig/elasticsearch、/usr/lib/systemd/system/elasticsearch.service里面的ES_COINIG_PATH为: /usr/share/elasticsearch/config
