### ISSUE TITLE
RPM安装的ES7.9.3集群，安装hanlp-7.9.3 启动报错

### ISSUE THREAD

**Issue by lnso** [KennFalcon/elasticsearch-analysis-hanlp#152]
HI 请协助看看，当前ISSUE类似现象已验证过，无效；
系统环境：
ES版本7.9.3 hanlp版本7.9.3
rpm方式安装es
elassticsearch-plugin install方式安装hanlp插件

安装插件后出现以下异常：
/usr/share/elasticsearch/bin/elasticsearch-plugin install file:///tmp/elasticsearch-analysis-hanlp-7.9.3.zip -b
future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.402.b06-1.el7_9.x86_64/jre] does not meet this requirement
-> Installing file:///tmp/elasticsearch-analysis-hanlp-7.9.3.zip
-> Downloading file:///tmp/elasticsearch-analysis-hanlp-7.9.3.zip
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission plugins/analysis-hanlp/data/- read,write,delete
* java.io.FilePermission plugins/analysis-hanlp/hanlp.cache read,write,delete
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission * read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed analysis-hanlp

# 启动异常
[2024-04-25T10:15:07,651][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [127.0.0.1] fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError: null
        at org.elasticsearch.plugin.analysis.hanlp.AnalysisHanLPPlugin.lambda$getTokenizers$0(AnalysisHanLPPlugin.java:67) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
        at org.elasticsearch.plugin.analysis.hanlp.AnalysisHanLPPlugin.getTokenizers(AnalysisHanLPPlugin.java:67) ~[?:?]
        at org.elasticsearch.common.NamedRegistry.extractAndRegister(NamedRegistry.java:54) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.indices.analysis.AnalysisModule.setupTokenizers(AnalysisModule.java:239) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.indices.analysis.AnalysisModule.<init>(AnalysisModule.java:85) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.node.Node.<init>(Node.java:375) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.node.Node.<init>(Node.java:277) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.9.3.jar:7.9.3]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.9.3.jar:7.9.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.9.3.jar:7.9.3]
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "data/dictionary/CoreNatureDictionary.tr.txt" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:1036) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:408) ~[?:?]
        at java.lang.SecurityManager.checkRead(SecurityManager.java:747) ~[?:?]
        at java.io.File.isFile(File.java:880) ~[?:?]
        at com.hankcs.hanlp.HanLP$Config.<clinit>(HanLP.java:335) ~[?:?]
        ... 18 more

**Comment by lnso** [comment]
已解决
与rpm安装es、jvm限制、数据目录权限相关；可做如下调整修复
# 安装插件
/usr/share/elasticsearch/bin/elasticsearch-plugin install file:///tmp/elasticsearch-analysis-hanlp-7.9.3.zip -b
# /usr/share/elasticsearch/bin/elasticsearch-plugin remove analysis-hanlp --purge
 
# 修改java权限(hanlp对java权限有过收缩)
vim /usr/share/elasticsearch/jdk/conf/security/java.policy
permission java.io.FilePermission "-","read";
 
# 修改数据目录权限
chown -R elasticsearch.elasticsearch /usr/share/elasticsearch/plugins/analysis-hanlp
 
# 处理es通过rpm包安装与hanlp install文件目录不兼容问题
mkdir -pv /usr/share/elasticsearch/config/analysis-hanlp/
chown -R elasticsearch.elasticsearch /usr/share/elasticsearch/config/analysis-hanlp/
ln -s /etc/elasticsearch/analysis-hanlp/hanlp.properties /usr/share/elasticsearch/config/analysis-hanlp/
