### ISSUE TITLE
es5x下跑不起来

### ISSUE THREAD

**Issue by jqsl2012** [KennFalcon/elasticsearch-analysis-hanlp#2]
异常信息为：`Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "*" "read,write")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_111]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_111]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_111]
        at java.lang.SecurityManager.checkPropertiesAccess(SecurityManager.java:1262) ~[?:1.8.0_111]
        at java.lang.System.getProperties(System.java:630) ~[?:1.8.0_111]
        at com.hankcs.hanlp.HanLP$Config.<clinit>(HanLP.java:306) ~[?:?]`

**Comment by KennFalcon** [comment]
抱歉，因ES5.x改动比较大，正在开发中

**Comment by KennFalcon** [comment]
经过研究这是java的权限设置问题，ES5.x之前的版本可以在elasticsearch.yml里设置security.manager.enabled为false。在ES5.x删除了该设置参数，暂时我们可以修改jdk中配置。以jdk8为例，在${JAVA_HOME}/jre/lib/security，修改java.policy，在grant{ }中添加下列内容：

_**permission java.security.AllPermission；**_

**Comment by hariag** [comment]
Hi @KennFalcon 这个临时的解决办法有潜在的安全风险，从长远来看你有插件层面解决这个问题的计划么？ 谢谢！
