### ISSUE TITLE
ES 5.2.2 版本运行报错 

### ISSUE THREAD

**Issue by secain** [KennFalcon/elasticsearch-analysis-hanlp#20]
[2019-02-19T08:09:05,566][INFO ][o.e.c.r.a.AllocationService] [w44JGC2] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[index][2]] ...]).
Feb 19, 2019 8:09:11 AM com.hankcs.hanlp.corpus.io.IOUtil readBytes
WARNING: 读取plugins/analysis-hanlp/data/dictionary/CoreNatureDictionary.txt.bin时发生异常java.io.FileNotFoundException: plugins/analysis-hanlp/data/dictionary/CoreNatureDictionary.txt.bin (No such file or directory)
Feb 19, 2019 8:09:11 AM com.hankcs.hanlp.dictionary.CoreDictionary load
WARNING: 核心词典plugins/analysis-hanlp/data/dictionary/CoreNatureDictionary.txt不存在！java.io.FileNotFoundException: plugins/analysis-hanlp/data/dictionary/CoreNatureDictionary.txt (No such file or directory)
[2019-02-19T08:09:11,715][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[w44JGC2][index][T#1]], exiting
java.lang.ExceptionInInitializerError: null
        at com.hankcs.hanlp.seg.common.Vertex.newB(Vertex.java:462) ~[?:?]
        at com.hankcs.hanlp.seg.common.WordNet.<init>(WordNet.java:73) ~[?:?]
        at com.hankcs.hanlp.seg.Viterbi.ViterbiSegment.segSentence(ViterbiSegment.java:40) ~[?:?]
        at com.hankcs.hanlp.seg.Segment.seg(Segment.java:507) ~[?:?]
        at com.hankcs.lucene.SegmentWrapper.next(SegmentWrapper.java:76) ~[?:?]
        at com.hankcs.lucene.HanLPTokenizer.incrementToken(HanLPTokenizer.java:94) ~[?:?]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:222) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:200) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:148) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:75) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:294) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:610) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.2.2.jar:5.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: 核心词典plugins/analysis-hanlp/data/dictionary/CoreNatureDictionary.txt加载失败
        at com.hankcs.hanlp.dictionary.CoreDictionary.<clinit>(CoreDictionary.java:44) ~[?:?]
        ... 20 more

https://www.jianshu.com/p/52c42cdab997 按照此文章解决了java权限（参照https://github.com/KennFalcon/elasticsearch-analysis-hanlp/issues/2）问题后，遇到另外的错误

**Comment by secain** [comment]
2. 安装数据包
release包中存放的为HanLP源码中默认的分词数据，若要下载完整版数据包，请查看HanLP Release。

数据包目录：ES_HOME/analysis-hanlp

这个应该还是装在plugin里吧？

**Comment by KennFalcon** [comment]
是的   这个还是在plugin目录，这个要和你hanlp.properties配置一致
