### ISSUE TITLE
v6.6.1 运行报错 看不懂

### ISSUE THREAD

**Issue by zhuyandong** [KennFalcon/elasticsearch-analysis-hanlp#26]
[2019-04-04T00:11:45,886][INFO ][o.e.n.Node               ] [rpmdWQa] started
[2019-04-04T00:12:10,126][INFO ][c.h.d.c.RemoteDictConfig ] [rpmdWQa] try load remote hanlp config from D:\webdev\es\ela
sticsearch-6.6.1\config\analysis-hanlp\hanlp-remote.xml
[2019-04-04T00:12:10,211][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [rpmdWQa] fatal error in thread [elasticse
arch[rpmdWQa][analyze][T#1]], exiting
java.lang.ExceptionInInitializerError: null
        at com.hankcs.hanlp.dictionary.CoreDictionary.<clinit>(CoreDictionary.java:35) ~[?:?]
        at com.hankcs.hanlp.seg.Other.DoubleArrayTrieSegment.<init>(DoubleArrayTrieSegment.java:45) ~[?:?]
        at com.hankcs.lucene.HanLPSpeedAnalyzer.createComponents(HanLPSpeedAnalyzer.java:31) ~[?:?]
        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:198) ~[lucene-core-7.6.0.jar:7.6.0 719cde97f846
40faa1e3525690d262946571245f - nknize - 2018-12-07 14:44:20]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.ja
va:267) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:252
) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.j
ava:170) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.j
ava:81) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.j
ava:115) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.
java:759) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.6.1
.jar:6.6.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "src\main\java" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_131]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_131]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_131]
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_131]
        at java.io.File.isDirectory(File.java:844) ~[?:1.8.0_131]
        at com.hankcs.hanlp.HanLP$Config.<clinit>(HanLP.java:342) ~[?:?]
        ... 14 more

**Comment by zhuyandong** [comment]
解决了。${JAVA_HOME}/jre/lib/security，修改java.policy，在grant{ }中添加下列内容：
permission java.security.AllPermission；
到centos服务器上试试。。

**Comment by KennFalcon** [comment]
这个权限问题会在后面插件版本修复
