### ISSUE TITLE
Error without stopwords.txt.bin

### ISSUE THREAD

**Issue by qwert321** [KennFalcon/elasticsearch-analysis-hanlp#57]
Error message:
Nov 03, 2019 2:33:27 PM com.hankcs.hanlp.corpus.io.IOUtil readBytes
WARNING: 读取plugins/analysis-hanlp/data/dictionary/stopwords.txt.bin时发生异常java.io.FileNotFoundException: plugins/analysis-hanlp/data/dictionary/stopwords.txt.bin (No such file or directory)
Nov 03, 2019 2:33:27 PM com.hankcs.dic.CoreStopWordDictionary <clinit>
SEVERE: 载入停用词词典plugins/analysis-hanlp/data/dictionary/stopwords.txt失败java.io.FileNotFoundException: plugins/analysis-hanlp/data/dictionary/stopwords.txt.bin (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at com.hankcs.hanlp.corpus.io.IOUtil.newOutputStream(IOUtil.java:696)
	at com.hankcs.dic.CoreStopWordDictionary.<clinit>(CoreStopWordDictionary.java:79)
	at com.hankcs.lucene.HanLPTokenizer.lambda$incrementToken$0(HanLPTokenizer.java:87)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
	at com.hankcs.lucene.HanLPTokenizer.incrementToken(HanLPTokenizer.java:86)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:271)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:246)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:165)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:82)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:113)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

in docker, with:
./bin/elasticsearch-plugin install https://github.com/KennFalcon/elasticsearch-analysis-hanlp/releases/download/v7.2.0/elasticsearch-analysis-hanlp-7.2.0.zip

**Comment by qwert321** [comment]
one error when install the plugin is as below.
Although some error messages, but seems install completed.
So, maybe any problem?

[root@cda01c2dcf36 elasticsearch]# ./bin/elasticsearch-plugin install https://github.com/KennFalcon/elasticsearch-analysis-hanlp/releases/download/v7.2.0/elasticsearch-analysis-hanlp-7.2.0.zip
-> Downloading https://github.com/KennFalcon/elasticsearch-analysis-hanlp/releases/download/v7.2.0/elasticsearch-analysis-hanlp-7.2.0.zip
[=================================================] 100%??
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission <<ALL FILES>> read,write,delete
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission * read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed analysis-hanlp

**Comment by qwert321** [comment]
my fault

**Comment by OYE93** [comment]
老兄 你这个怎么解决的？感谢
