### ISSUE TITLE
HanLPTokenizer term==null未设置offset，重入会报错

### ISSUE THREAD

**Issue by seanlei** [KennFalcon/elasticsearch-analysis-hanlp#61]
HanLPTokenizer line 75 term=null后需要
totalOffset+=segment.offset;
再返回false

**Comment by KennFalcon** [comment]
麻烦具体贴一下报错样例请求，以及报错信息

**Comment by seanlei** [comment]
`java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1086,endOffset=1088,lastStartOffset=1089 for field 'content'
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:843) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:442) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:406) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:250) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:494) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1594) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1213) ~[lucene-core-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:03]
	at org.elasticsearch.index.engine.InternalEngine.addDocs(InternalEngine.java:1129) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:1074) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:904) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:792) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:764) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:721) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:256) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:159) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:191) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:116) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:77) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:923) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:108) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:398) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:316) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$15(IndexShard.java:2606) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:112) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:269) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:236) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2580) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:864) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:312) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:275) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:257) [x-pack-security-7.3.1.jar:7.3.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:315) [x-pack-security-7.3.1.jar:7.3.1]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:703) [elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) [elasticsearch-7.3.1.jar:7.3.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.3.1.jar:7.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
`
使用copy_to多个字段copy到一个字段时，报错。es 7.3.1。修改如下
 `            if (term == null) {
               totalOffset+=segment.offset;
                 return false;
             }`

**Comment by KennFalcon** [comment]
抱歉，我用copy_to未发现这个问题，请问一下插件版本也是7.3.1吗，内容长度大约多少字    我再详细测试我一下

**Comment by seanlei** [comment]
settings
```
{"settings":{"index":{"analysis":{"char_filter":{"repalce_date":{"pattern":"([〇\\d\\u4e00-\\u9fa5]{4}年[〇\\d\\u4e00-\\u9fa5]*月[〇\\d\\u4e00-\\u9fa5]*日)","type":"pattern_replace","replacement":""}},"analyzer":{"deli_hanlp":{"tokenizer":"deli_hanlp_tokenizer"},"default":{"type":"hanlp"}},"tokenizer":{"deli_hanlp_tokenizer":{"enable_custom_config":"true","enable_place_recognize":"true","type":"hanlp","enable_name_recognize":"true","enable_organization_recognize":"true","enable_offset":"true"},"semicolon_tokenizer":{"pattern":"[,;]","type":"pattern"}}}}}}
```
mappings
```
{"properties":{"content":{"type":"text","norms":false,"analyzer":"deli_hanlp"},"fact":{"type":"text","norms":false,"copy_to":["content"],"analyzer":"deli_hanlp"},"judgeJury":{"type":"text","norms":false,"copy_to":["content"],"analyzer":"deli_hanlp"},"judgeResult":{"type":"text","norms":false,"copy_to":["content"],"analyzer":"deli_hanlp"},"litigant":{"type":"text","norms":false,"copy_to":["content"],"analyzer":"deli_hanlp"},"trialDescribe":{"type":"text","norms":false,"copy_to":["content"],"analyzer":"deli_hanlp"},"viewPoint":{"type":"text","norms":false,"copy_to":["content"],"analyzer":"deli_hanlp"}}}
```
测试body
```
{"index":{"_index":"test_leiyu","_type":"_doc","_id":"f67174d96dd39ee2bf22f8e13a24c131"}}
{      "viewPoint": "本院认为，综合双方当事人的诉辩主张，本案争议的焦点问题是：一、宝都公司欠付苏通公司工程款的数额及利息应当如何确定；二、苏通公司是否享有对涉案工程的价款优先受偿权；三、苏通公司剩余物资的价值应当如何确定。\n关于第一个焦点问题。本院认为，苏通公司与宝都公司于2013年5月21日签订的建设工程施工合同系双方真实意思表示，且不违反法律法规的强制性规定，合法有效。合同签订后，苏通公司对涉案工程进行了施工，后因种种原因，双方合同无法继续履行。宝都公司与苏通公司于2015年1月29日在青岛市黄岛区城市建设局的主持下签订了《协议书》，解除了双方之间的建设工程施工合同，并就合同解除后的相关事宜进行了约定。该《协议书》系双方真实意思表示，双方均应当按照《协议书》中的约定履行各自义务。\n《协议书》约定：双方同意审计局抽取委托的青岛和正工程管理咨询有限公司对实际完成工程量自行编制工程结算书，双方无条件认可该工程造价咨询机构对亚德里亚海湾二期项目的结算值，并作为最终结算依据。据此，青岛和正工程管理咨询有限公司于2015年2月13日依各方委托就涉案工程作出青和建鉴（2015）第001-0010号《基本建设工程结算鉴证报告》，其鉴定结论为：亚德里亚海湾项目二期工程结算总造价（退甲供钢筋）为60688312.52元。苏通公司虽对该鉴定结论不予认可，但其未能提交有效证据证明该鉴定过程存在程序违法或结论明显依据不足的情形，故，本院对该鉴定结论予以确认。\n因上述鉴定结论曾做出说明“所有签证暂未计取，由宝都和苏通另行解决”，故，本院依苏通公司的申请依法委托青岛正和信工程造价咨询有限公司对涉案工程的签证部分造价进行鉴定。青岛正和信工程造价咨询有限公司于2018年3月5日作出青正和信字2017-1-1117-1号《亚德里亚海湾项目二期工程签证造价司法鉴定报告》，其鉴定结论为：该项目工程造价值为1187074.45元（其中：甲方、监理均已签字工程造价值为667620.80元；甲方未签字、监理已签字工程造价值为519452.65元）。依照苏通公司与宝都公司签订《亚德里亚海湾项目二期工程备案合同补充协议》中第四条第2项、第4项的约定，未经发包方签字确认的签证不得作为竣工结算的依据。因此，本院对于该鉴定报告中甲方、监理均已签字的工程造价值予以确认，涉案工程签证部分的造价应为667620.8元。\n综合上述两部分鉴定结论，本院认定涉案工程的造价为61355933.32元（60688312.52元＋667620.8元）。\n对于宝都公司的已付工程款数额，双方均无异议的已付款额为39875016.22元",    "trialDescribe": "原告苏通建设集团有限公司（以下简称苏通公司）因与被告山东宝都房地产开发有限公司（以下简称宝都公司）建设工程施工合同纠纷一案，向本院提起诉讼。本院受理后依法组成合议庭，依法适用普通程序，公开开庭进行了审理。原告的委托诉讼代理人孔靖，被告的委托诉讼代理人王宇到庭参加了诉讼。本院现已审理终结",    "fact": "苏通公司向本院提出诉讼请求：1、依法判令宝都公司向苏通公司支付工程欠款45534669.11元，并以22000370.75元为基数，自2015年2月14日起至2018年7月31日止，按银行同期贷款利率的两倍计算欠款利息，利息为7456292.3元；2、依法判令宝都公司向苏通公司支付工程进度款利息4259924.68元；3、判令苏通公司对承包工程拍卖或折价的价款优先受偿；4、判令宝都公司向苏通公司赔偿窝工损失16426851.96元；5、判令宝都公司向苏通公司支付现场接收物资价款627523.99元；6、宝都公司承担本案的诉讼费用。事实与理由：2013年5月21日，苏通公司与宝都公司签订《青岛市建设工程施工合同》一份，合同约定工程名称：亚德里亚海湾项目二期工程；工程地点：青岛开发区天目山路以西、银沙滩路以北；工程规模及结构特征：包括6＃、8＃、10＃楼及沿街商业网点、配套公建、多层ＡＢＣＤ住宅、商务中心及地下车库、总面积161525平方米，框剪结构；工程质量标准：合格；合同另对其他事项作了约定。合同签订后，苏通公司即依约组织人员进场施工。施工过程中，因宝都公司未能依约支付工程进度款导致工程无法继续施工。后双方协商一致解除了双方之间的建设工程施工合同关系，并将部分物资移交给宝都公司。经结算苏通公司已完成工程造价85409685.33元（暂定，已扣除甲供材），扣除宝都公司已支付的39875016.22元（实际以庭审对账为准），宝都公司尚欠45534699.11元，恳请依法判决。\n被告苏通公司辩称：1、苏通公司在诉状所述的解除施工合同的原因与事实不符。由于苏通公司在施工过程中，工作准备不足，管理混乱，导致工地长期停工，且不断出现工程质量问题，因此宝都公司被迫于2015年1月13日向苏通公司发出解除施工合同的通知。为了妥善解决施工合同解除后的结算、工程移交及资料交接等事宜，在青岛市黄岛区城市建设局的主持下，宝都公司与苏通公司及青岛市黄岛区城市建设局于2015年1月29日签订了协议书（以下简称“三方协议”），对此苏通公司与宝都公司均有义务严格履行；2、依据三方协议，苏通公司尚未满足结算付款的条件。依据三方协议第四条，苏通公司应在三方协议签订后5日内对全部工程、工地和所有工程资料进行清点、检验后移交宝都公司，否则宝都公司不予办理结算、付款等后续事务。时至今日，苏通公司仍未将全部工程资料移交给宝都公司，导致宝都公司无法进行阶段性验收备案，因此产生的损失与日俱增；3、根据三方协议完成的《结算鉴证报告书》，苏通公司所主张的工程款数额严重错误。根据三方协议第一条、第二条，甲乙双方共同委托的鉴证机构按约定时间出具了报告书，对此双方应无条件认可，按照此报告书，宝都公司的工程欠款不足2000万元。因苏通公司至今未履行交付全部工程资料的前提义务，因此宝都公司有权拒绝支付剩余工程款；4、苏通公司主张的欠款利息、窝工损失没有依据。在苏通公司无权索要工程款的情况下，苏通公司主张的利息损失没有事实依据。因苏通公司的原因导致工期延迟，苏通公司应向宝都公司承担违约责任。此外，根据三方协议约定，除工程质量外，宝都公司与苏通公司均不得追究对方其他任何责任；5、苏通公司主张的优先受偿权，已超过了法定期间，依法不应得到支持。如果按照施工合同约定的竣工日期计算，苏通公司起诉时已超过了法定的6个月期间；即使根据相关司法精神，按照解除施工合同并退场的时间开始起算，也超过了6个月，因此苏通公司主张的优先受偿权不应得到支持；6、苏通公司对现场遗留物资的价值严重高估，宝都公司不予认可。请求依法查明事实，驳回苏通公司的诉讼请求。\n当事人围绕诉讼请求依法提交了证据，根据当事人陈述和经审查确认的证据，本院认定事实如下：\n2013年5月21日，苏通公司与宝都公司签订《青岛市建设工程施工合同》一份，合同编号为2013-118，合同约定：一、工程概况工程名称：亚德里亚海湾项目二期工程。工程地点：青岛开发区天目山路以西、银沙滩路以北。工程规模及结构特征：包括6＃、8＃、10＃楼及沿街商业网点、配套公建、多层ＡＢＣＤ住宅、商务中心及地下车库、总面积161525平方米，框剪结构；二、工程承包范围：图纸设计范围内的土石方工程、地基与基础工程、主体工程、电气工程、给排水工程、采暖供热工程、通风空调工程、楼地面工程、内墙抹灰工程、外墙工程、防水工程、门窗工程、消防工程（仅消火栓系统，消防系统的预埋预留，其他不含）；三、合同工期开工日期：2013年5月21日（实际开工时间以监理单位下达开工令为准）。竣工日期：2015年7月11日。合同工期总日历天数780天；四、质量标准工程质量标准：合格；五、合同价款合同总价：245331101.55元。合同另对其他事项作了约定。双方均认可涉案工程经过了招投标程序，系先由苏通公司中标，而后签订了上述合同。\n2013年5月23日，苏通公司与宝都公司签订《亚德里亚海湾项目二期工程备案合同补充协议》一份，该协议第四条第2项约定：本合同所称“现场签证”，是指根据施工现场的实际情况，对施工方法、施工作业数量、施工条件等不需要变更施工图设计的事项作出的调整和确认。现场签证由承包人根据现场实际情况填写现场签证单，经发包人代表和监理工程师现场核实签字，并由发包人工程部、成本复核加盖发包人“公章”确认后生效。四十五日内，逾期未返还，视为认可；第4项约定：没有按照以上程序办理并生效的设计变更、现场签证，不得进行施工，不得作为工程价款调整、工程进度款计算和竣工结算的依据。该补充协议附件六第（6）项约定：“收到竣工结算报告及结算资料并对竣工结算报告及结算资料确认后90天内支付至双方确认的工程结算值的95%”；第（7）项约定：“剩余5%作为工程保修金。竣工验收满二年无质量问题且承包人已履行工程质量保修书约定义务的，20天内无息返还至保修金的70%；满五年无质量问题且承包人已履行工程质量保修书约定义务的，20天内无息返还至全部保修金”。\n上述合同签订后，苏通公司对涉案工程进行了施工。2015年1月13日，宝都公司向苏通公司发出《解除合同通知书》一份，苏通公司称并未收到该通知。\n2015年1月29日，宝都公司作为甲方、苏通公司作为乙方与丙方青岛市黄岛区城市建设局共同签订《协议书》一份。该协议载明：“甲方开发的亚德里亚海湾二期项目（金沙滩壹号），位于青岛市黄岛区天目山路以西，银沙滩以北，施工总承包单位为乙方，现就合同解除后的退场及工程结算有关事宜订立本协议。第一条甲乙双方同意审计局抽取委托的青岛和正工程管理咨询有限公司对实际完成工程量自行编制工程结算书，结算依据甲乙双方2013年5月23日签订的《亚德里亚海湾项目二期工程备案合同补充协议》执行，双方法人授权委派一名领导两名工作人员参加，无条件配合该工程造价咨询单位结算工作，一日内按要求提供相关工程技术资料，及时组织查看现场，丙方派人全程见证。工程造价咨询单位根据工程实际情况，有权决定工程结算依据。甲乙双方均不得干涉，确保其独立、公正。第二条甲乙双方无条件认可该工程造价咨询机构对亚德里亚海湾二期项目的结算值，并作为最终结算依据。第三条甲方应在本协议签订后一日内转账300万元人民币至丙方指定账户作为农民工工资保证金，审计单位完成农民工工资审核后，丙方直接转账至乙方账户。此保证金多退少补，若审核后甲方欠乙方工程款中农民工工资多于300万，则甲方应在结算值确定后二日内将超出部分支付乙方；若审核后少于300万，则丙方应在结算值确定后一日内将超出部分退还甲方。第四条结算报告应在本协议签订后十五日内完成，结算值确定后甲乙双方必须签字，同时，本协议签订后五日内乙方将施工现场租赁的塔吊等设备及周转材料撤出工地，同时对全部工程、工地和所有工程资料进行清点、检验后移交甲方，丙方负责监督撤场与交接，并监督其完整性和合格性。如乙方不履行本条款，甲方不予办理结算、付款等后续事务。第五条甲方应提前准备好乙方的工程结算款项，在结算值确定后的七日内将结算值的95%工程款扣减300万农民工工资保证金、已支付款项、甲方代缴各项费用、各种罚款以及各种不合格扣款后的剩余款项付至丙方指定账户，（各种罚款截止2015年1月12日已经发生的，质量问题需经建设、施工、监理三方施工现场清点过程中查验确认）；剩余5%作为工程保修金并按原合同约定支付乙方。如甲方不履行该条款，乙方不协助办理竣工验收备案手绣，丙方不予竣工验收备案。第六条甲方按协议约定支付第五条所述工程款后，乙方全权协助甲方办理项目竣工验收，丙方配合甲方办理竣工验收备案手续。在后续施工及竣工验收备案过程中，如出现乙方工程资料和工程质量问题，由丙方负责协调乙方追缴和处理，如乙方不配合，给甲方造成损失的，由丙方协调乙方解决。第七条工程资料及工地移交完成，并且乙方提供甲方合格发票后，丙方立即安排将第五条所述工程款转账至乙方帐户。第八条在协议履行期间，乙方不得发生上访事件。第九条本协议履行完毕后，除工程质量外，互不追究其他任何责任。任何一方不履行本协议义务，应当赔偿给其他方造成的损失第十条本协议一式六份，三方各执两份，三方法定代表人或授权代表签字并加盖公章后生效，同时原2015年1月17日三方签订的《协议书》作废。自本协议签订之日起，甲乙双方签订的施工总承包合同及补充协议解除”。合同下方有甲、乙、丙三方盖章并由各方代表签字确认。\n上述协议签订后，苏通公司、宝都公司依照协议约定对涉案工程进行了交接，并于2015年2月3日签署《亚德里亚海湾二期工程工地移交书》。\n2015年2月13日，青岛和正工程管理咨询有限公司依各方委托就涉案工程作出青和建鉴（2015）第001-0010号《基本建设工程结算鉴证报告》。其鉴证意见为：6＃楼及附属网点工程总造价为20603257.03元（含甲供钢筋预算价格），扣除甲供钢筋后工程最终结算造价为16452743.25元；8＃楼工程总造价为20950125.89元（含甲供钢筋预算价格），扣除甲供钢筋后工程最终结算造价为17326651.07元；10＃楼工程总造价为23180112.05元（含甲供钢筋预算价格），扣除甲供钢筋后工程最终结算造价为18897943.34元；洋房Ａ工程总造价为940297.73元（含甲供钢筋预算价格），扣除甲供钢筋后工程最终结算造价为843777.15元；洋房Ｂ工程总造价为1453116.26元（含甲供钢筋预算价格），扣除甲供钢筋后工程最终结算造价为1375676.93元;洋房Ｃ工程总造价为751201.58元（含甲供钢筋预算价格），扣除甲供钢筋后工程最终结算造价为647612.26元;洋房Ｄ工程总造价为1193296.35元（含甲供钢筋预算价格），扣除甲供钢筋后工程最终结算造价为1065837.20元；商务中心工程总造价为2034746.73元（含甲供钢筋预算价格）扣除甲供钢筋后工程最终结算造价为1818550.39元；高层车库工程总造价为1376691.40元（含甲供钢筋预算价格），扣除甲供钢筋后工程最终结算造价为1366594.72元；洋房车库工程总造价为898565.12元（含甲供钢筋预算价格），扣除甲供钢筋后工程最终结算造价为892926.72元。在青和建鉴（2015）第002-0010号《基本建设工程结算鉴证报告》的说明事项中均注明：“根据备案合同补充协议约定，本工程中现场签证需经发包人代表和监理工程师现场核实签字，并由发包人工程部、成本部复核加盖发包人公章确认后生效。现提供资料甲方工程部及成本部签字不完整，且无发包人公章确认，所有签证暂未计取，由宝都和苏通另行解决”。该报告作出后，宝都公司对该报告的鉴定结论无异议，苏通公司对该报告的鉴定结论不予认可。苏通公司认为，青岛和正工程管理咨询有限公司在对本案所涉工程进行鉴定的过程中，曾受到宝都公司的威胁和干扰，宝都公司违反协议约定，青岛和正工程管理咨询有限公司作出的鉴定报告不客观。苏通公司为此提交青岛和正工程管理咨询有限公司法定代表人李军和苏通公司经理杭颂谦之间的谈话录音予以证明。宝都公司质证认为，该证据不能证明是李军和杭颂谦之间的通话录音，其中所谓宝都公司威胁要求将工程造价做到5000万元系李军的一面之词，没有证据证明。而从鉴定结果看，涉案工程去掉甲供材造价就达6000多万元，因此是客观公正的。本案审理过程中，苏通公司据此申请对涉案工程的造价进行重新鉴定。本院经审查认为，苏通公司未提交有效证据证明该鉴定结论存在程序违法或结论明显依据不足的情形，故，对其鉴定申请未予准许。\n本案审理过程中，苏通公司向本院提出鉴定申请，申请对涉案工程的签证部分造价进行鉴定。本院依法委托青岛正和信工程造价咨询有限公司对苏通公司的申请事项进行鉴定。2018年3月5日，青岛正和信工程造价咨询有限公司作出青正和信字2017-1-1117-1号《亚德里亚海湾项目二期工程签证造价司法鉴定报告》，其鉴定结论为：该项目工程造价值为1187074.45元（其中：甲方、监理均已签字工程造价值为667620.80元；甲方未签字、监理已签字工程造价值为519452.65元）。该报告作出后，宝都公司对该报告的鉴定结论无异议，但认为报告中提到的宝都公司未签字而监理已签字的部分共计519452.65元，不应得到支持。苏通公司对该报告的鉴定结论提出了47项异议，对此青岛正和信工程造价咨询有限公司的鉴定人员出庭接受了质询，并作出了书面答复。苏通公司未再就此提出异议。\n苏通公司主张宝都公司已付工程款数额为39875016.22元，宝都公司对此不予认可，其认为其已付款数额为42221016.22元。宝都公司主张除苏通公司已提交的付款明细外，还有宝都公司替魏吉荣扣留借款冲抵工程款2346000元。为此，宝都公司提交2015年1月30日《收款收据》一份、《借款协议》一份及转账凭证一宗并申请魏吉荣出庭作证以证明其主张。苏通公司认为，转账凭证显示打款时间是2014年6月至7月期间，而借款协议的签订时间是2014年9月份，从而可以看出，先有个人之间的转帐记录，而借款协议是后来补签的。因此，对借款的真实性有异议。如果是苏通公司向魏吉荣本人借款，应当以苏通公司的名义签订相关协议，款项也应当汇入苏通公司的帐户，而该款项汇入了朱丽丽的帐户，而协议的签订人是朱善飞，因此，该笔借款不能对苏通公司发生法律效力。\n2015年2月1日，苏通公司与宝都公司签署《苏通现场留下物资表》，该表显示遗留物资为：配电箱防护（标准配置）3个、配电箱（总配电箱）1台（备注6＃楼总配电箱总开1250Ａ）、配电箱（总配电箱）1台（备注10＃楼总配电箱总开630Ａ）、配电箱（分配电箱）1台（备注8＃楼分配电箱总开250Ａ）、6＃楼主电缆（3＊95＋2＊50）110米（备注铜芯电缆）、10＃楼主电缆（3＊185＋2＊95）158米（备注铜芯电缆）、8＃楼主电缆（3＊70＋2＊35）82米（备注铝芯电缆）、会所1Ｆ配电箱（1Ｆ2Ｆ临电总箱）1台、会所主屏幕电缆（5＊10）30米、会所电梯电缆（5＊16）40米、板房（21.86Ｍ＊6.1Ｍ＊6Ｍ）5栋（备注6间＊2层／每栋）、厕所（14.7Ｍ＊6Ｍ＊3Ｍ）1栋、6＃楼北门值班室（2.65Ｍ＊3.23Ｍ＊2.6Ｍ）1间、围挡（2Ｍ＊0.4Ｍ）547块、围挡脚手架管943.5米、围挡卡子507个、6＃楼北侧大门（6Ｍ＊3Ｍ）1个、6＃楼北侧小门（1.2Ｍ＊2Ｍ）1个、洋房南侧围挡（2Ｍ＊0.4Ｍ）111块（备注质监站所有）……。苏通公司主张上述遗留物资的价值分别为：配电箱防护（标准配置）3个15000元、配电箱（总配电箱）1台（备注6＃楼总配电箱总开1250Ａ）1800元、配电箱（总配电箱）1台（备注10＃楼总配电箱总开630Ａ）1200元、配电箱（分配电箱）1台（备注8＃楼分配电箱总开250Ａ）750元、6＃楼主电缆（3＊95＋2＊50）110米（备注铜芯电缆）28600元、10＃楼主电缆（3＊185＋2＊95）158米（备注铜芯电缆）75050元、8＃楼主电缆（3＊70＋2＊35）82米（备注铝芯电缆）15170元、会所1Ｆ配电箱（1Ｆ2Ｆ临电总箱）1台350元、会所主屏幕电缆（5＊10）30米1080元、会所电梯电缆（5＊16）40米2320元、板房（21.86Ｍ＊6.1Ｍ＊6Ｍ）5栋（备注6间＊2层／每栋）367248元、厕所（14.7Ｍ＊6Ｍ＊3Ｍ）1栋25210.08元、6＃楼北门值班室（2.65Ｍ＊3.23Ｍ＊2.6Ｍ）1间2396.66元、围挡（2Ｍ＊0.4Ｍ）547块32820元、围挡脚手架管943.5米14624.25元、围挡卡子507个17745元、6＃楼北侧大门（6Ｍ＊3Ｍ）1个15000元、6＃楼北侧小门（1.2Ｍ＊2Ｍ）1个4500元、洋房南侧围挡（2Ｍ＊0.4Ｍ）111块（备注质监站所有）6660元。以上物资合计627523.99元，因遗留给宝都公司，宝都公司应当予以偿付。宝都公司对上述物资的数量及价值予以确认。但认为，《苏通现场留下物资表》上面的物资，并非全部是苏通公司所有，其中：第19项洋房南侧围挡，已经注明属于质监站所有；第11-18项临时设施，属于上一承包方青岛通力建设集团有限公司所建，由宝都公司移交给苏通公司使用，并约定从应支付的第三笔工程款中全额扣除费用，但截至目前，宝都公司并未扣除该临时设施的费用。且临时设施的费用已包含在措施费当中，不应该重复计算；第1、2、3、4、8项对应的配电箱，也是宝都公司提供的，与苏通公司无关；第6项电缆为宝都公司提供，如果是苏通公司采购，应提交宝都公司的批价单，以及采购时的付款发票等资料。苏通公司主张的现场遗留物资价值全部归自己所有是错误的，不应得到支持",    "judgeResult": "一、被告山东宝都房地产开发有限公司于本判决生效之日起10日内支付原告苏通建设集团有限公司工程款18413120.43元，并以此为基数，按中国人民银行同期贷款利率，支付自2015年2月20日至本判决生效之日止的利息；\n二、被告山东宝都房地产开发有限公司于本判决生效之日起10日内支付原告苏通建设集团有限公司遗留物资价值141320元；\n三、驳回原告苏通建设集团有限公司其他诉讼请求。\n如果未按本判决指定的期间履行给付金钱义务，应当依照《中华人民共和国民事诉讼法》第二百五十三条之规定，加倍支付迟延履行期间的债务利息。\n案件受理费402633元，由原告苏通建设集团有限公司负担287595元，由被告山东宝都房地产开发有限公司负担115038元。保全费5000元、鉴定费33754.94元，被告山东宝都房地产开发有限公司负担。\n如不服本判决，可在判决书送达之日起十五日内向本院递交上诉状，并按对方当事人的人数提供副本，上诉于山东省高级人民法院",    "judgeJury": "审判长陈明明\n审判员马喆\n审判员徐明\n二〇一八年八月三十一日\n书记员孔怡\n书记员李珊珊",    "litigant": "\n\n 原告：苏通建设集团有限公司，住所地江苏省海门市海门镇光华大厦＊＊楼＊＊。\n\n 法定代表人：蔡国新，董事长。\n\n 委托诉讼代理人：孔靖，山东琴岛律师律师所律师。\n\n 委托诉讼代理人：张文钧，上海普世律师事务所律师。\n\n 被告：山东宝都房地产开发有限公司，，住所地青岛市经济技术开发区长江中路＊＊\n\n 法定代表人：张志波，总经理。\n\n 委托诉讼代理人：王宇，上海锦天城（青岛）律师事务所律师。\n\n 委托诉讼代理人：李鸣晗，上海锦天城（青岛）律师事务所实习律师。\n\n"  }
```
调用bulk api做插入报错
es版本7.3.1 插件版本7.3.1

**Comment by KennFalcon** [comment]
感谢提出的修改建议，新版本会采用并修复改bug

**Comment by KennFalcon** [comment]
适配最新版本7.5.0时，修复该问题
