### ISSUE TITLE
添加内容时报错：startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=1,lastStartOffset=8 for field

### ISSUE THREAD

**Issue by NicolJiang** [KennFalcon/elasticsearch-analysis-hanlp#65]
开了这些选项：
"enable_traditional_chinese_mode": true,
          "enable_normalization": true,
          "enable_translated_name_recognize": true,
          "enable_custom_dictionary": true,
          "enable_remote_dict": true,
          "enable_name_recognize": true,
          "enable_japanese_name_recognize": true,
          "enable_place_recognize": true,
          "enable_organization_recognize": true,
          "enable_index_mode": true,
          "enable_custom_config": true

建立索引时没问题，但添加内容时会报错：
startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=1,lastStartOffset=8 for field

**Comment by KennFalcon** [comment]
麻烦把版本号和错误样例贴一下

**Comment by NicolJiang** [comment]
版本号：7.4.2

{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=1,lastStartOffset=22 for field 'url'"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=1,lastStartOffset=22 for field 'url'"
  },
  "status" : 400
}

**Comment by KennFalcon** [comment]
麻烦贴一下错误数据和错误请求

**Comment by NicolJiang** [comment]
[2019-12-04T11:20:21,998][DEBUG][o.e.a.b.TransportShardBulkAction] [izwz99d7x8qidgxmjmd211z] [search_log_v2][3] failed to execute bulk item (index) index {[search_log_v2][_doc][7JPszm4BR4ZP11eVSHjp], source[{
  "url": "除了百度网盘还有什么下载软件Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36",
  "domain": "xxxx.com",
  "is": [
    "type:one"
  ],
  "ip": [
    "117.34.13.12"
  ],
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36",
  "rf": "",
  "timestamp": "15445056056141"
}]}
java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=1,lastStartOffset=22 for field 'url'
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:843) ~[lucene-core-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:442) ~[lucene-core-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:406) ~[lucene-core-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:250) ~[lucene-core-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:495) ~[lucene-core-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1594) ~[lucene-core-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1213) ~[lucene-core-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
        at org.elasticsearch.index.engine.InternalEngine.addDocs(InternalEngine.java:1138) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:1075) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:911) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:796) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:768) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:725) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:258) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:161) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:193) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:118) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:79) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:917) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:108) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:394) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:316) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$21(IndexShard.java:2753) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:112) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:285) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:237) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2727) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:858) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:312) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:275) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:257) [x-pack-security-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:315) [x-pack-security-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:752) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.4.2.jar:7.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]

**Comment by KennFalcon** [comment]
索引结构麻烦发一下

**Comment by NicolJiang** [comment]
{
  "search_log_v2" : {
    "mappings" : {
      "properties" : {
        "domain" : {
          "type" : "text",
          "analyzer" : "my_path",
          "fielddata" : true
        },
        "ip" : {
          "type" : "ip"
        },
        "is" : {
          "type" : "keyword"
        },
        "rf" : {
          "type" : "text",
          "analyzer" : "my_index",
          "search_analyzer" : "my_search",
          "fielddata" : true
        },
        "timestamp" : {
          "type" : "date",
          "format" : "epoch_millis"
        },
        "ua" : {
          "type" : "text",
          "analyzer" : "my_index",
          "search_analyzer" : "my_search",
          "fielddata" : true
        },
        "url" : {
          "type" : "text",
          "analyzer" : "my_index",
          "search_analyzer" : "my_search",
          "fielddata" : true
        }
      }
    }
  }
}

**Comment by NicolJiang** [comment]
{
  "settings": {
    "number_of_shards": 5,
    "number_of_replicas": 1,
    "analysis": {
      "analyzer": {
        "my_keyword": {
          "char_filter": [
            "my_html_strip"
          ],
          "tokenizer": "keyword",
          "filter": [
            "lowercase"
          ]
        },
        "my_index": {
          "type": "custom",
          "char_filter": [
            "my_html_strip"
          ],
          "tokenizer": "my_hanlp_index",
          "filter": [
            "lowercase"
          ]
        },
        "my_search": {
          "type": "custom",
          "char_filter": [
            "my_html_strip"
          ],
          "tokenizer": "my_hanlp_search",
          "filter": [
            "lowercase"
          ]
        },
        "my_path": {
          "tokenizer": "path_hierarchy",
          "filter": [
            "lowercase"
          ]
        }
      },
      "tokenizer": {
        "my_hanlp_search": {
          "type": "hanlp",
          "enable_traditional_chinese_mode": true,
          "enable_normalization": true,
          "enable_translated_name_recognize": true,
          "enable_custom_dictionary": true,
          "enable_remote_dict": true,
          "enable_name_recognize": true,
          "enable_japanese_name_recognize": true,
          "enable_place_recognize": true,
          "enable_organization_recognize": true,
          "enable_custom_config": true
        },
        "my_hanlp_index": {
          "type": "hanlp",
          "enable_traditional_chinese_mode": true,
          "enable_normalization": true,
          "enable_translated_name_recognize": true,
          "enable_custom_dictionary": true,
          "enable_remote_dict": true,
          "enable_name_recognize": true,
          "enable_japanese_name_recognize": true,
          "enable_place_recognize": true,
          "enable_organization_recognize": true,
          "enable_index_mode": true,
          "enable_custom_config": true
        }
      },
      "char_filter": {
        "my_html_strip": {
          "type": "html_strip"
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "url": {
        "type": "text",
        "analyzer": "my_index",
        "search_analyzer": "my_search",
        "fielddata": true
      },
      "domain": {
        "type": "text",
        "analyzer": "my_path",
        "fielddata": true
      },
      "is": {
        "type": "keyword"
      },
      "ip": {
        "type": "ip"
      },
      "ua": {
        "type": "text",
        "analyzer": "my_index",
        "search_analyzer": "my_search",
        "fielddata": true
      },
      "rf": {
        "type": "text",
        "analyzer": "my_index",
        "search_analyzer": "my_search",
        "fielddata": true
      },
      "timestamp": {
        "type": "date",
        "format": "epoch_millis"
      }
    }
  }
}

**Comment by KennFalcon** [comment]
问一下，用多少条数据bulk请求的，我用单条测试还是正常

**Comment by NicolJiang** [comment]
这是我的请求：
curl -X "POST" "https://es:9200/search_log_v2/_doc/?pretty" \
     -H 'Content-Type: application/json' \
     -d $'{
  "domain": "xxx.com",
  "is": [
    "type:one"
  ],
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36",
  "rf": "",
  "timestamp": "15445056056141",
  "ip": [
    "117.34.13.12"
  ],
  "url": "除了百度网盘还有什么下载软件Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36"
}'

请求后的反馈：
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=1,lastStartOffset=22 for field 'url'"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=1,lastStartOffset=22 for field 'url'"
  },
  "status" : 400
}

**Comment by KennFalcon** [comment]
我这边测试单条没有问题，这边代码修改了copy_to导致的offset问题，但是我看你的请求里面也没有用到，你可以用master，修改版本号，再测试一下看看会不会出现这个问题
