### ISSUE TITLE
windows10 环境下安装报错

### ISSUE THREAD

**Issue by pandora-iuz** [KennFalcon/elasticsearch-analysis-hanlp#72]
`
PS D:\elk\elasticsearch-7.5.1> .\bin\elasticsearch-plugin.bat install file:///D:\elk\iyouju-elasticsearch-analysis-hanlp-master.zip
-> Downloading file:///D:\elk\iyouju-elasticsearch-analysis-hanlp-master.zip
[=================================================] 100%??
Exception in thread "main" java.nio.file.NoSuchFileException: D:\elk\elasticsearch-7.5.1\plugins\.installing-11570651505465590675\plugin-descriptor.properties
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:374)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:425)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:159)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:724)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:803)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:786)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:232)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
`

**Comment by muxiaobai** [comment]
如果是测试，可以直接解压，然后把config先放到es_home/config

**Comment by KennFalcon** [comment]
报错的原因是你ES plugins目录下有非插件的目录，你删掉再次安装试一下

**Comment by KennFalcon** [comment]
如有其他问题，请重开issue

**Comment by chenzhigang9521** [comment]
> 

非插件目录，是指任何目录么

> 如有其他问题，请重开issue



> 报错的原因是你ES plugins目录下有非插件的目录，你删掉再次安装试一下

我也遇到这个问题了，plugins目录下只有ik和拼音的分词插件，没有非插件的目录
