### ISSUE TITLE
elasticsearch 6.8.0~6.8.6没有对应的elasticsearch-analysis-hanlp版本

### ISSUE THREAD

**Issue by superboy1984** [KennFalcon/elasticsearch-analysis-hanlp#73]
我用的es6.8.0，最近要升级到6.8.6，另外elasticsearch-analysis-hanlp最接近的6.7.1版本，hanlp版本是1.7.3的，作者可以发布6.8.0~6.8.6的使用hanlp 1.7.6版本的elasticsearch-analysis-hanlp么？
感谢！！！

**Comment by superboy1984** [comment]
哈哈哈，虽然不懂JAVA，只会C#，但是还是搞定了。过程如下，供有需要的人参考：
1、官网下载eclipse，安装JDK8。
3、打开eclipse，起启页选择【Checkout projects from Git】，然后输入插件的git地址，一直“下一步”，最后选择 import as general project。
2、修改pom.xml这三项：
        <elasticsearch.version>6.8.0</elasticsearch.version>
        <javac.src.version>1.8</javac.src.version>
        <javac.target.version>1.8</javac.target.version>
3、修改src/main/java/org/elasticsearch/index/analysis/HanLPTokenizerFactory.java 40行为：
super(indexSettings, name, settings);
4、右键 pom.xml -- Run as -- maven install，编译完成即可。编译生成的文件就是\target\releases\elasticsearch-analysis-hanlp-6.8.0.zip

但是分词过程中，报了下面的错。什么状况呢？
[2020-03-04T00:20:26,448][INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][114] overhead, spent [496ms] collecting in the last [1.3s]
[2020-03-04T00:20:35,293][INFO ][c.h.d.ExtMonitor         ] [node-1] reloading hanlp custom dictionary
[2020-03-04T00:20:36,464][INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][124] overhead, spent [320ms] collecting in the last [1s]
[2020-03-04T00:20:37,809][INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][125] overhead, spent [475ms] collecting in the last [1.3s]
[2020-03-04T00:20:39,078][INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][126] overhead, spent [485ms] collecting in the last [1.2s]
[2020-03-04T00:20:42,223][INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][129] overhead, spent [290ms] collecting in the last [1.1s]
[2020-03-04T00:20:42,928][ERROR][c.h.u.CustomDictionaryUtility] [node-1] hanlp custom dictionary main path [plugins/analysis-hanlp/data/dictionary/custom/CustomDictionary.txt] is not exist
java.io.FileNotFoundException: plugins/analysis-hanlp/data/dictionary/custom/CustomDictionary.txt.bin (权限不够)
        at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_212]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_212]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_212]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101) ~[?:1.8.0_212]
        at com.hankcs.hanlp.corpus.io.IOUtil.newOutputStream(IOUtil.java:696) ~[?:?]
        at com.hankcs.utility.CustomDictionaryUtility.loadMainDictionary(CustomDictionaryUtility.java:83) ~[?:?]
        at com.hankcs.utility.CustomDictionaryUtility.reload(CustomDictionaryUtility.java:41) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_212]
        at com.hankcs.dic.ExtMonitor.run(ExtMonitor.java:55) [elasticsearch-analysis-hanlp-6.8.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[2020-03-04T00:20:42,953][INFO ][c.h.d.c.DictionaryFileCache] [node-1] begin write down hanlp custom dictionary file cache, file path: /usr/local/es/elasticsearch-6.8.0/plugins/analysis-hanlp/hanlp.cache, custom dictionary file list: [DictionaryFile{path='plugins/analysis-hanlp/data/dictionary/custom/CustomDictionary.txt', lastModified=1571233272000}, DictionaryFile{path='plugins/analysis-hanlp/data/dictionary/custom/ModernChineseSupplementaryWord.txt', lastModified=1571233272000}, DictionaryFile{path='plugins/analysis-hanlp/data/dictionary/custom/ChinesePlaceName.txt', lastModified=1571233272000}, DictionaryFile{path='plugins/analysis-hanlp/data/dictionary/custom/PersonalName.txt', lastModified=1571233272000}, DictionaryFile{path='plugins/analysis-hanlp/data/dictionary/custom/OrganizationName.txt', lastModified=1571233272000}, DictionaryFile{path='plugins/analysis-hanlp/data/dictionary/custom/ShanghaiPlaceName.txt', lastModified=1571233272000}, DictionaryFile{path='plugins/analysis-hanlp/data/dictionary/person/nrf.txt', lastModified=1571233272000}]
