### ISSUE TITLE
6.8.5  载入停用词词典 失败

### ISSUE THREAD

**Issue by RichardLiu0926** [KennFalcon/elasticsearch-analysis-hanlp#76]
[2020-03-20T21:30:18,752][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [4j67C1P] fatal error in thread [elasticsearch[4j67C1P][analyze][T#1]], exiting
java.lang.ExceptionInInitializerError: null
        at com.hankcs.lucene.HanLPTokenizer.lambda$incrementToken$0(HanLPTokenizer.java:88) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
        at com.hankcs.lucene.HanLPTokenizer.incrementToken(HanLPTokenizer.java:87) ~[?:?]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:275) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:252) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:170) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:81) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:115) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) ~[elasticsearch-6.8.5.jar:6.8.5]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.5.jar:6.8.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.RuntimeException: 载入停用词词典plugins/analysis-hanlp/data/dictionary/stopwords.txt失败
        at com.hankcs.dic.CoreStopWordDictionary.<clinit>(CoreStopWordDictionary.java:85) ~[?:?]
        ... 13 more

**Comment by fjqwonders** [comment]
加载stopwords.txt，启动es的用户是不是没有权限
