### ISSUE TITLE
hanlp.cache问题

### ISSUE THREAD

**Issue by yang1** [KennFalcon/elasticsearch-analysis-hanlp#8]
非常感谢hanlp分词插件。
我这边有个问题，如果有hanlp.cache文件，我重新启动es，会报错。请问下是什么原因？
如果删除hanlp.cache文件，就可以正常运行，但需要时间重新加载hanlp的词典。
错误：
**[2018-07-24T17:46:22,115][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node1] fatal error in thread [elasticsearch[node1][generic][T#2]], exiting
java.lang.NoClassDefFoundError: org/elasticsearch/core/internal/io/IOUtils**
	at com.hankcs.dic.cache.DictionaryFileCache.lambda$loadCache$0(DictionaryFileCache.java:60) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
	at com.hankcs.dic.cache.DictionaryFileCache.loadCache(DictionaryFileCache.java:45) ~[?:?]
	at com.hankcs.dic.Dictionary.<init>(Dictionary.java:45) ~[?:?]
	at com.hankcs.dic.Dictionary.initial(Dictionary.java:52) ~[?:?]
	at com.hankcs.cfg.Configuration.<init>(Configuration.java:54) ~[?:?]
	at org.elasticsearch.index.analysis.HanLPTokenizerFactory.<init>(HanLPTokenizerFactory.java:31) ~[?:?]
	at org.elasticsearch.index.analysis.HanLPTokenizerFactory.getHanLPNLPTokenizerFactory(HanLPTokenizerFactory.java:47) ~[?:?]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:361) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildTokenizerFactories(AnalysisRegistry.java:176) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:154) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.index.IndexService.<init>(IndexService.java:145) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:363) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:448) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.indices.IndicesService.verifyIndexMetadata(IndicesService.java:481) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.gateway.Gateway.performStateRecovery(Gateway.java:135) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.gateway.GatewayService$1.doRun(GatewayService.java:229) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.1.jar:5.6.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
**Caused by: java.lang.ClassNotFoundException: org.elasticsearch.core.internal.io.IOUtils**
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
	... 22 more

**Comment by KennFalcon** [comment]
这个缓存是为了热更新hanlp自定义字典缓存，麻烦提供一下ES的版本

**Comment by yang1** [comment]
我用的是5.6.1的版本，但我换上6.3.1的版本后，重启hanlp.cache后没问题的，谢谢啦。

我还想问下，hanlp热加载怎么配置？有没有向ansj那样做api热加载的？
比如：
/_ansj/flush/dic: 更新全部词典。包括用户自定义词典,停用词典,同义词典,歧义词典,crf
http://fonova-hadoop5:9201/_ansj/flush/dic?key=dic

**Comment by KennFalcon** [comment]
热更新只要根据Hanlp正常添加自定义字典方式添加就好，可以查看https://github.com/hankcs/HanLP，第8小节用户自定义词典

**Comment by KennFalcon** [comment]
目前自定义词典增加了一种远程更新的方式，解决了medcl的IK分词器设置方式，可以使用一下
