### ISSUE TITLE
有适配ES7.9的版本吗？elasticsearch-analysis-hanlp7.5安装报错了

### ISSUE THREAD

**Issue by agentxpt** [KennFalcon/elasticsearch-analysis-hanlp#88]
Exception in thread "main" java.net.UnknownHostException: data
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.Socket.connect(Socket.java:606)
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:962)
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:924)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1019)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1005)
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:311)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:417)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:449)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:329)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:251)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by aboutZZ** [comment]
附自己编译的7.9.3版本：[下载](https://wws.lanzous.com/ilyiojg8nlc)

**Comment by agentxpt** [comment]
搞定了，谢谢！
